apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: abort-http
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
    fault:
      abort:
        percentage:
          value: 40
        httpStatus: 502
