apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin-org
spec:
  hosts:
  - httpbin.org
  ports:
  - name: http
    number: 80
    targetPort: 443
    protocol: HTTP
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: httpbin-org-origination
spec:
  host: httpbin.org
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin-org-uuid
spec:
  hosts:
   - httpbin.org
  http:
  - match:
    - uri:
        exact: /uuid
    directResponse:
      status: 503
      body:
        string: "Upstream temporary outage"
