apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin-mirroring
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
        subset: v1
      weight: 100
    mirror:
      host: httpbin.default.svc.cluster.local
      subset: v2
    mirrorPercentage:
      value: 100.0
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: httpbin-mirroring
spec:
  host: httpbin.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

