apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: retry
spec:
  hosts:
    - delay-http-echo.default.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 4
        perTryTimeout: 1s
        retryOn: "5xx,connect-failure,refused-stream,gateway-error,reset"
      route:
        - destination:
            host: delay-http-echo.default.svc.cluster.local
            port:
              number: 8088
