apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin-delay-all
spec:
  hosts:
  - httpbin.default.svc.cluster.local
  http:
  - fault:
      delay:
        fixedDelay: 2s
        percentage:
          value: 100
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
